version: '3.8'

name: llm_local

services:
  ollama:
    image: ollama/ollama:latest
    container_name: ollama
    ports:
      - "11434:11434"
    volumes:
      - ollama_data:/root/.ollama
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
    environment:
      - NVIDIA_VISIBLE_DEVICES=all
      - NVIDIA_DRIVER_CAPABILITIES=compute,utility

  # model-init:
  #   image: alpine:latest
  #   container_name: qwen3-init
  #   command: sh -c "sleep 5 && ollama pull qwen3:8b-q6_K"
  #   depends_on:
  #     - ollama
  #   environment:
  #     - OLLAMA_HOST=http://ollama:11434

  open-webui:
    image: ghcr.io/open-webui/open-webui:main
    container_name: open-webui
    ports:
      - "9090:8080"
    volumes:
      - open_webui_data:/app/backend/data
    depends_on:
      - ollama
    environment:
      - OLLAMA_API_URL=http://ollama:11434/api
      - INITIAL_VISITOR_MODE=true
      - DISABLE_SIGNUP=true

volumes:
  ollama_data:
  open_webui_data: