name: llm_local
services:
  ollama:
    image: ollama/ollama:latest
    container_name: ollama
    ports:
      - "11434:11434"
    volumes:
      - ollama_data:/root/.ollama
    environment:
      - NVIDIA_VISIBLE_DEVICES=all
      - NVIDIA_DRIVER_CAPABILITIES=compute,utility
      - OLLAMA_FLASH_ATTENTION=1
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
        # limits:
        #   cpus: '4'
        #   memory: 16G
    # healthcheck:
    #   test: ["CMD", "curl", "-f", "http://localhost:11434"]
    #   interval: 30s
    #   timeout: 10s
    #   retries: 3

  # model-init:
  #   image: ollama/ollama:latest
  #   container_name: ollama-model-init
  #   command: sh -c "sleep 10 && ollama pull qwen2.5-coder:14b-instruct-q3_K_S"
  #   depends_on:
  #     ollama:
  #       condition: service_healthy
  #   environment:
  #     - OLLAMA_HOST=http://ollama:11434
  #   volumes:
  #     - ollama_data:/root/.ollama
  #   deploy:
  #     resources:
  #       reservations:
  #         devices:
  #           - driver: nvidia
  #             count: 1
  #             capabilities: [gpu]

volumes:
  ollama_data: