# docker-compose.ui.yml
services:
  open-webui:
    extends:
      file: docker-compose.base.yml
      service: ollama  # Чтобы не повторять сетевые настройки
    image: ghcr.io/open-webui/open-webui:main
    container_name: open-webui
    ports:
      - "9090:8080"
    volumes:
      - open_webui_data:/app/backend/data
    depends_on:
      - ollama
      # ollama:
        # condition: service_healthy
      # model-init:
      #   condition: service_completed_successfully
    environment:
      - OLLAMA_API_URL=http://ollama:11434/api
      - INITIAL_VISITOR_MODE=true
      - DISABLE_SIGNUP=true
      - WEBUI_SECRET_KEY=12345
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080"]
      interval: 1m

volumes:
  open_webui_data: